# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2017-04-07 03:30
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Collaborators',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('repo_name', models.CharField(max_length=200)),
                ('repo_description', models.CharField(max_length=200)),
                ('collaborators', models.IntegerField(default=0)),
            ],
        ),
        migrations.CreateModel(
            name='Populars',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('repo_name', models.CharField(max_length=200)),
                ('stars', models.IntegerField(default=0)),
                ('sort', models.IntegerField(default=0)),
                ('type', models.CharField(choices=[('GN', 'General'), ('CO', 'Colombian')], default='GN', max_length=2)),
            ],
        ),
    ]
